# Sample documents, generated by GPT-5

DOCUMENT_1 = """
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='UTF-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
    <title>Wireless Optogenetic Apparatus for Remote Modulation of Neural Activity</title>
  </head>
  <body>
    <h1>Claims</h1>
    <p>
      1. A wireless optogenetic apparatus for remotely modulating neural activity, the apparatus comprising:
    </p>
    <p>
      a housing containing light-conversion media configured to up-convert infrared or near-infrared electromagnetic radiation into visible wavelengths, the housing being made of biocompatible material and having optical transparency and low mass;
    </p>
    <p>
      the light-conversion media comprising lanthanide-doped nanoparticles or functionally equivalent up-conversion particles that transform infrared or near-infrared radiation to visible light;
    </p>
    <p>
      a form factor configured for placement proximate to a neuron of a subject, the form factor including a tapered section to concentrate optical emission;
    </p>
    <p>
      the apparatus further including a plurality of optical apertures to enable multiplexed control of neural responses, and a sealed enclosure retaining the light-conversion media.
    </p>
    <p>
      2. The apparatus of claim 1, wherein the biocompatible material comprises glass or polydimethylsiloxane.
    </p>
    <p>
      3. The apparatus of claim 1, wherein the apparatus is suitable for both human and non-human subjects.
    </p>
    <p>
      4. A radiation delivery system for actuating the apparatus of claim 1 at a distance, the radiation delivery system comprising:
    </p>
    <p>
      a radiation emitter, a positioning mechanism, a detector, and a controller;
    </p>
    <p>
      the radiation delivery system being configured to track and illuminate the wireless apparatus with infrared or near-infrared radiation to permit real-time adjustments and precise spatial targeting;
    </p>
    <p>
      the radiation delivery system being further configured to modify irradiation parameters including wavelength, intensity, and pulse duration, and to accommodate a range of subject motions.
    </p>
    <p>
      5. The radiation delivery system of claim 4, wherein the system's adaptability supports diverse experimental paradigms and subject conditions.
    </p>
    <p>
      6. A method for remotely modulating neural activity, the method comprising:
    </p>
    <p>
      positioning the wireless optogenetic apparatus of claim 1 adjacent to a neuron of a subject;
    </p>
    <p>
      actuating the wireless optogenetic apparatus using the radiation delivery system of claim 4;
    </p>
    <p>
      converting infrared or near-infrared electromagnetic radiation to visible light via the light-conversion media within the wireless optogenetic apparatus;
    </p>
    <p>
      effecting complex neural modulation through the plurality of optical apertures of the wireless optogenetic apparatus.
    </p>
    <p>
      7. The method of claim 6, wherein actuating the wireless optogenetic apparatus comprises tracking and irradiating the apparatus with infrared or near-infrared radiation to enable real-time adjustment and precise targeting.
    </p>
    <p>
      8. The method of claim 6, wherein actuating the wireless optogenetic apparatus comprises varying irradiation properties including wavelength, intensity, and pulse duration.
    </p>
  </body>
</html>
</DOCTYPE>
"""

DOCUMENT_2 = """
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='UTF-8' />
    <meta name='viewport' content='width=device-width, initial-scale=1.0' />
    <title>Adaptive Haptic Feedback System for Wearable Devices</title>
  </head>
  <body>
    <h1>Claims</h1>
    <p>
      1. An adaptive haptic feedback system for a wearable device, the system comprising:
    </p>
    <p>a wearable housing configured to be worn on a limb of a user;</p>
    <p>
      a plurality of haptic actuators disposed within the wearable housing, the haptic actuators comprising at least one of eccentric rotating mass motors, linear resonant actuators, piezoelectric benders, or electroactive polymer elements;
    </p>
    <p>
      a sensor suite comprising at least one inertial measurement unit, a photoplethysmography sensor, and a skin temperature sensor configured to generate physiological and motion data of the user;
    </p>
    <p>
      a controller operatively coupled to the sensor suite and the haptic actuators, the controller configured to generate a haptic output pattern based on a context model derived from the physiological and motion data;
    </p>
    <p>
      a machine learning module stored in memory and executable by the controller, the machine learning module configured to adapt the haptic output pattern over time according to user feedback and detected user state; and
    </p>
    <p>
      a communication interface configured to exchange data with an external computing device.
    </p>
    <p>
      2. The system of claim 1, wherein the context model classifies user state into at least one of resting, walking, running, cycling, sleeping, and high-stress.
    </p>
    <p>
      3. The system of claim 1, wherein the controller is configured to modulate haptic intensity, frequency, waveform, spatial distribution, and duration based on the classified user state.
    </p>
    <p>
      4. The system of claim 1, wherein the wearable housing comprises a flexible strap with segmented actuator zones arranged circumferentially to provide directional cues.
    </p>
    <p>
      5. The system of claim 1, wherein the machine learning module employs reinforcement learning to optimise haptic output patterns using implicit feedback inferred from changes in heart rate variability and motion regularity.
    </p>
    <p>
      6. The system of claim 1, wherein the communication interface comprises Bluetooth Low Energy configured to receive application notifications and navigation instructions from the external computing device.
    </p>
    <p>
      7. The system of claim 1, further comprising a calibration routine configured to map user-specific perceptual thresholds for haptic intensity across the actuator zones.
    </p>
    <p>
      8. The system of claim 1, wherein the sensor suite further comprises a skin conductance sensor configured to detect sympathetic arousal for stress-responsive haptic adjustment.
    </p>
    <p>
      9. The system of claim 1, wherein the haptic actuators are driven with phase-offset control to synthesise virtual motion sensations along the limb.
    </p>
    <p>
      10. The system of claim 1, wherein the controller applies energy-aware scheduling to reduce average power consumption below 10 mW during idle monitoring.
    </p>
    <p>
      11. A method for providing adaptive haptic feedback with the system of claim 1, the method comprising:
    </p>
    <p>
      acquiring physiological and motion data from the sensor suite;
    </p>
    <p>
      inferring a user state using the context model;
    </p>
    <p>
      selecting a haptic output pattern corresponding to the inferred user state;
    </p>
    <p>
      driving the plurality of haptic actuators to render the selected haptic output pattern; and
    </p>
    <p>
      updating the machine learning module using implicit or explicit user feedback to adjust future haptic output patterns.
    </p>
    <p>
      12. The method of claim 11, wherein the user state is inferred in real time with a sliding window of 2 to 10 seconds of sensor data.
    </p>
    <p>
      13. The method of claim 11, wherein explicit user feedback is received through a companion application interface providing accept, dismiss, and intensity adjustment inputs.
    </p>
    <p>
      14. The method of claim 11, wherein the haptic output pattern comprises navigation cues encoded as spatially sequential actuation indicating turn direction and distance-to-manoeuvre.
    </p>
    <p>
      15. The method of claim 11, wherein the haptic output pattern is attenuated during detected sleep to maintain notifications below a user-specific arousal threshold.
    </p>
    <p>
      16. A non-transitory computer-readable medium storing instructions that, when executed by the controller of the system of claim 1, cause the controller to:
    </p>
    <p>
      preprocess sensor data by filtering, normalisation, and feature extraction;
    </p>
    <p>
      perform user state classification with a lightweight neural network;
    </p>
    <p>
      map classified states to parameterised haptic patterns; and
    </p>
    <p>
      adapt the parameter mapping using reinforcement signals derived from physiological responses and user inputs.
    </p>
    <p>
      17. The system of claim 1, wherein the controller enforces a skin safety policy by limiting actuator duty cycle and maximum surface temperature.
    </p>
    <p>
      18. The system of claim 1, wherein actuator placement and control create perceivable patterns for accessibility notifications for users with hearing impairments.
    </p>
    <p>
      19. The system of claim 1, wherein the wearable housing is water-resistant to at least IP67 and comprises hypoallergenic skin-contact materials.
    </p>
    <p>
      20. The system of claim 1, wherein the communication interface supports over-the-air updates to modify the context model and haptic pattern library.
    </p>
  </body>
</html>
</DOCTYPE>
"""
